#!/usr/bin/env python

import datetime,os,requests

post_dir = 'posts/_posts/'

todays_date = datetime.datetime.today().strftime('%Y-%m-%d')
print("\n\n")
try:
    title = raw_input("That's great. What's the title ? (Avoid special characters)   :   ")
except:
    title = input("That's great. What's the title ? (Avoid special characters)   :   ")
print("\n\n")
file_name = post_dir + todays_date + "-" + title.strip().replace(" ", "-") + ".md"
os.system("touch " + file_name)


try:
    cover_term = raw_input("Cover Image Term : ")
except:
    try:
        cover_term = input("Cover Image Term : ")
    except:
        cover_term = "nature"


write_str = """---
layout: post
title: post_title
tags: 
cover_url: https://source.unsplash.com/random?cover_term
cover_meta: 
  (c) UNSPLASH
color_scheme: tango
mathjax: true
mathjax: True
---
<style TYPE="text/css">
code.has-jax {font: inherit; font-size: 100%; background: inherit; border: inherit;}
</style>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
    tex2jax: {
        inlineMath: [['$','$']],
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'] // removed 'code' entry
    }
});
MathJax.Hub.Queue(function() {
    var all = MathJax.Hub.getAllJax(), i;
    for(i = 0; i < all.length; i += 1) {
        all[i].SourceElement().parentNode.className += ' has-jax';
    }
});
</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_HTML-full"></script>


<br/>
Feeling generous ? Help me write more blogs like this :)  

<center>
<script type="text/javascript" src="https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js" data-name="bmc-button" data-slug="abhinandandubey" data-color="#FFDD00" data-emoji=""  data-font="Cookie" data-text="Buy me a coffee" data-outline-color="#000" data-font-color="#000" data-coffee-color="#fff" ></script>
</center>
<br/>
<br/>

"""

# print("Fetching NASA Image of the day...\n")


# API_KEY = open("/Users/abhinandandubey/NASA_API_KEY.key", "r").read().strip()
# data = requests.get(url = "https://api.nasa.gov/planetary/apod?api_key=" + API_KEY).json() 
# print(data["title"].encode("ascii"), data["url"].encode("ascii"))
# try:
#     write_str = write_str.replace("post_title", title)
#     write_str = write_str.replace("cover_meta_text", data["title"].encode("ascii"))
#     write_str = write_str.replace("cover_meta_url", data["url"].encode("ascii"))
# except:
#     pass
try:
    write_str = write_str.replace("post_title", title)
    write_str = write_str.replace("cover_meta_text", cover_term)
    write_str = write_str.replace("cover_meta_url", cover_term)
    write_str = write_str.replace("cover_term", cover_term)
except:
    pass

f = open(file_name, "a")
f.write(write_str)

print("\nCreated " + file_name)
