#!/usr/bin/env python

import glob
import os

post_dir = 'posts/_posts/'
tag_dir = 'posts/tags/'

filenames = glob.glob(post_dir + '*md')

total_tags = []
for filename in filenames:
    f = open(filename, 'r')
    crawl = False
    for line in f:
        if crawl and line[:5] == "tags:":
            current_tags = line[5:].strip().split(" ")
            total_tags.extend(current_tags)
            crawl = False
            break
        if line.strip() == '---':
            if not crawl:
                crawl = True
            else:
                crawl = False
                break
    f.close()
total_tags = set(total_tags)
print(total_tags)

old_tags = glob.glob(tag_dir + '*.md')
for tag in old_tags:
    print("Found : " + str(tag))
    os.remove(tag)
   
if not os.path.exists(tag_dir):
   os.makedirs(tag_dir)

for tag in total_tags:
   tag_filename = tag_dir + tag + '.md'
   f = open(tag_filename, 'a')
   write_str = '---\nlayout: post-list\ntitle: \"' + tag + '\"\nfilter:\n - by_tag: \"' + tag + '\"\n---\n'
   f.write(write_str)
   f.close()
print("Tags generated, count", total_tags.__len__())
